### PR TITLE
Perform registration even though component already required

### LINKED ISSUE #34: Auto register and already required files
Hi all :v:

We've encountered some unexpected behaviour with auto register.

Let's say I have `Services` folder with 2 files:

```ruby
# 1.rb
class One
end
```

```ruby
# 2.rb
require './1.rb'
class Two
end
```

Both files are inside of some auto register folder. And in this case load order matters, cause if `2.rb` is auto registered (and so required) first, `1.rb` will not be registered at all because [`Kernel.require(component.path)`](https://github.com/dry-rb/dry-system/blob/master/lib/dry/system/container.rb#L454) will return false. Preventing [this code](https://github.com/dry-rb/dry-system/blob/master/lib/dry/system/auto_registrar.rb#L29) from registering component.

So, maybe `Kernel.require(component.path) && yield` should be replaced with:

```ruby
Kernel.require(component.path)
yield
```

Otherwise why it is done with `&&`?

Thanks for help

### LINKED ISSUE #35: [discussion] Find a way to have component registered even though it was previously required
Hi!

I've recently entered an issue of which it seems some changes need to be applied [here][1] in order to get it to work. I mean the possiblity to register component even though it was required somewhere else. Consider inheritance as an example – either base class has to be registered first so the order of registering components _must be_ explicit or an extra `require` statement is needed in the subclass so the parent constant is known. Although `Kernel.require(component.path) && yield` is very clever I suppose it may be inconsistent due to the [guard][2] statement present at the method beggining – in essence, if the component exists, go away. Actually the block shouldn't ever be performed if key associated to given component already exists. However, I may not be familiar with all of the use cases, but simple change `Kernel.require(component.path); yield` vastly changes the whole registration process.

From what I've found, the `yield` concerns only use cases when component has to be registered, e.g. [here][3] and [here][4], however in this case [guard][3] forbids registration if a component already exists so we're covered, or at least that's my way of thinking.

The current container apporach prefers aggregation, whereas in certain cases inheritance might be a solution as well. 

What do you guys think about it ?

ps. I ran `Kernel.require(component.path); yield` in my local environment and didn't get into any troubles. The `dry-system` specs have passed as well.

[1]: https://github.com/dry-rb/dry-system/blob/34de07d1ad5f7d0344b9610877334eca74cd70ff/lib/dry/system/container.rb#L454
[2]: https://github.com/dry-rb/dry-system/blob/34de07d1ad5f7d0344b9610877334eca74cd70ff/lib/dry/system/container.rb#L448
[3]: https://github.com/dry-rb/dry-system/blob/34de07d1ad5f7d0344b9610877334eca74cd70ff/lib/dry/system/container.rb#L481
[4]: https://github.com/dry-rb/dry-system/blob/902c0f3c4f6313502ba0f50e68fec51066b33943/lib/dry/system/auto_registrar.rb#L31

### PR DESCRIPTION
**Pull request by blelump**
Hi ! 

Here's a small change discussed in #35 

Closes #35 
Closes #34

### CODE REVIEW

**Comment by blelump** [comment]
Uhm, for some reason Rubinius build fails, but it seems unrelated.

**Comment by solnic** [comment]
Could you rebase on top of master and add a test for this use case?

**Comment by blelump** [comment]
@solnic , sure, done.

**Comment by solnic** [comment]
Thanks. Are you planning to work on a test too?

**Comment by blelump** [comment]
@solnic , aww right. Sorry I've missed that part – will add it tomorrow.

**Comment by blelump** [comment]
@solnic , added. Not sure on that [part][1] though, because it hits container directly.

[1]: https://github.com/dry-rb/dry-system/pull/36/commits/0b502d9fbbb55e0a19ea26930c24c7ec58af9b56#diff-662a8ca0583951270ed8221c1ef6b5b4R66

**Comment by vladra** [comment]
Also closes #34

**Comment by solnic** [comment]
Merged. Thank you :)

**Pull request merged**
