### PR TITLE
Add args and hash strategies from auto inject to dependency graph plugin

### PR DESCRIPTION
**Pull request by davydovanton**
Hey, I forgot to add other strategies to dry-system dependency graph. We need to do it if we want to detect injectors for graph

### CODE REVIEW

**Comment by timriley** [comment]
@davydovanton This change looks 👍 to me.

I wonder why the tests are failing, though... @flash-gordon would you have any idea?

**Comment by solnic** [comment]
rebase and it’ll pass on CI

**Comment by davydovanton** [comment]
@solnic done, thanks for help!

**Comment by solnic** [comment]
@davydovanton could you expand `spec/integration/container/plugins/dependency_graph_spec.rb` to cover this addition?

**Pull request closed without merging**
